name: Build Runtime on Windows
on: push

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Checkout runtime
      uses: actions/checkout@v2.0.0
    - name: Build
      run: .\build.cmd -subset clr
    - name: Test all
      run: .\src\tests\run.cmd x64 checked
