name: Build Runtime on Windows
on: push

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Checkout runtime
      uses: actions/checkout@v2.0.0
    - name: Build
      run: .\build.cmd -subset clr
    - name: Pack
      run: |
        cd ..
        dir
        Compress-Archive runtime
        dir
    - uses: actions/upload-artifact@v4
      with:
        name: build_dir
        path: runtime.zip
